CREATE TABLE IF NOT EXISTS HELLOREPO.BANK_INTEREST_INCOME (  
    BANK_NAME VARCHAR(255) NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary Key',
    TERMS DATETIME COMMENT '기간',
    TERMS_UNIT VARCHAR(30) '기간단위',
    INTEREST_EARNING_ASSETS DOUBLE COMMENT '이자수익자산',
    INTEREST_REVENUE  DOUBLE COMMENT '이자수익',
    INTEREST_BEARNING_LIABILITIES DOUBLE COMMENT '이자비용부채',
    INTEREST_EXPENSE DOUBLE COMMENT '이자비용'
) DEFAULT CHARSET UTF8 COMMENT '은행예대규모기록';

SELECT * FROM HELLOREPO.BANK_INTEREST_INCOME ;
INSERT INTO HELLOREPO.BANK_INTEREST_INCOME (
    BANK_NAME,TERMS,TERMS_UNIT,INTEREST_EARNING_ASSETS,INTEREST_REVENUE,INTEREST_BEARNING_LIABILITIES,INTEREST_EXPENSE
) VALUES ('카카오뱅크','2019-01-01','Y','19193789000000','494598000000','20711908000000','247036000000') ; 


